application: times-tables
version: 2
runtime: python
api_version: 1

handlers:
- url: /javascripts
  static_dir: javascripts
- url: /stylesheets
  static_dir: stylesheets
- url: /robots.txt
  static_files: static/robots.txt
  upload: static/robots.txt
- url: .*
  script: main.py
